

@url = http://localhost:7071
#@url = https://todoapi01ms.azurewebsites.net

### Get all todos
GET {{url}}/todos


### Get todo by id 
GET {{url}}/todos/103

### Create todo
POST {{url}}/todos
content-type: application/json

{
    "id": 1244,
    "title": "Go for a walk and talk"
}

### Update todo (just the title)
PUT {{url}}/todos/10
content-type: application/json

{
    "title" : "Do some more work"
}

### Update todo (just done)
PUT {{url}}/todos/1
content-type: application/json

{
    "done" : true
}

### Delete todo
DELETE {{url}}/todos/3
